version: '3'

services:
  app:
    container_name: infura_api
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      PORT: 8080
      PROJECT_ID: 'xxx'
    volumes:
      - .:/app
